version: "3"
services:
  server:
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:nde-demo.localhost;PathPrefix:/termennetwerk"
      - "traefik.port=5401"
    networks:
      - traefik

networks:
  traefik:
    external: true
