apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nde-termennetwerk-frontend-route
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nde.51-105-200-91.nip.io`) && PathPrefix(`/termennetwerk`)
      kind: Rule
      services:
        - name: nde-termennetwerk-frontend-service
          port: 80
  tls:
    certResolver: default
    options: {}